name: Security Scan

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run TruffleHog
        run: |
          # Install trufflehog from the official GitHub release since PyPI version might be outdated
          wget https://github.com/trufflesecurity/trufflehog/releases/latest/download/trufflehog_linux_amd64.tar.gz
          tar -xzf trufflehog_linux_amd64.tar.gz
          sudo mv trufflehog /usr/local/bin/
          
          # Run the security scan on the current directory
          trufflehog filesystem --regex --max-depth 1 ./